server:
  port: 7776
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7776/eureka/
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456

