server:
  port: 8080
spring:
  application:
    name: pn-user-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true
